version: 2

sources:
  - name: adv_works
    schema: adv_works
    description: Banco de dados bruto do ERP, da empresa Adventure Works
    tables:
      - name: person_address
        description: tabela de cadastro de endereço
        columns:
          - name: addressid
            description: id
          - name: addressline1
            description: logradouro
          - name: addressline2
            description: complemento     
          - name: city
            description: cidade  
          - name: stateprovinceid
            description: estado
          - name: postalcode
            description: código postal
          - name: spatiallocation
          - name: rowguid
          - name: modifieddate
            description: Data da modificação

      - name: person_countryregion
        description: tabela de cadastro de pais
        columns:
          - name: countryregioncode
            description: id único
          - name: name
            description: Nome do Pais
          - name: modifieddate
            description: Data da modificação

      - name: production_product
        description: Tabela de cadastro de produtos.
        columns:
          - name: productid
            description: chave única da tabela.
          - name: name
            description: Nome do Produto
          - name: productnumber
            description: Número de série do produto
          - name: sellstartdate
            description: Data de inicio da venda do produto
          - name: productsubcategoryid
            description: Chave estrangeira para a tabela product.productsubcategory
          - name: modifieddate
            description: Data de modificação do registro

      - name: production_productsubcategory
        description: Tabela de cadastro de subcategoria de produtos.
        columns:
          - name: productsubcategoryid
            description: chave única da tabela.
          - name: productcategoryid
            description: Chave estrangeira para a tabela product.productcategory
          - name: name
            description: Nome da subcategoria
  
      - name: production_productcategory
        description: Tabela de cadastro de categoria de produtos.
        columns:
          - name: productcategoryid
            description: chave única da tabela.
          - name: name
            description: Nome da subcategoria
                        