version: 2

sources:
  - name: adv_works
    schema: adv_works
    description: Banco de dados bruto do ERP, da empresa Adventure Works
    tables:
      - name: person_address
        description: tabela de cadastro de endereço
        columns:
          - name: addressid
            description: id
          - name: addressline1
            description: logradouro
          - name: addressline2
            description: complemento     
          - name: city
            description: cidade  
          - name: stateprovinceid
            description: estado
          - name: postalcode
            description: código postal
          - name: spatiallocation
          - name: rowguid
          - name: modifieddate
            description: Data da modificação

      - name: person_stateprovince
        description: Tabela de cadastro de estados/provínciais
        columns:
          - name: stateprovinceid
            description: Chave primária da tabela.
          - name: stateprovincecode
            description: Sigla do estado.
          - name: countryregioncode
            description: Sigla do pais, utilizado como FK para a batela person_countryregion.
          - name: isonlystateprovinceflag
          - name: name
            description: Nome do Estado/Província.
          - name: territoryid
            description: FK para a tabela sales.SalesTerritory.
          - name: rowguid
          - name: modifieddate
          
      - name: person_countryregion
        description: tabela de cadastro de pais
        columns:
          - name: countryregioncode
            description: id único
          - name: name
            description: Nome do Pais
          - name: modifieddate
            description: Data da modificação

      - name: production_product
        description: Tabela de cadastro de produtos.
        columns:
          - name: productid
            description: chave única da tabela.
          - name: name
            description: Nome do Produto
          - name: productnumber
            description: Número de série do produto
          - name: sellstartdate
            description: Data de inicio da venda do produto
          - name: productsubcategoryid
            description: Chave estrangeira para a tabela product.productsubcategory
          - name: modifieddate
            description: Data de modificação do registro

      - name: production_productsubcategory
        description: Tabela de cadastro de subcategoria de produtos.
        columns:
          - name: productsubcategoryid
            description: chave única da tabela.
          - name: productcategoryid
            description: Chave estrangeira para a tabela product.productcategory
          - name: name
            description: Nome da subcategoria
  
      - name: production_productcategory
        description: Tabela de cadastro de categoria de produtos.
        columns:
          - name: productcategoryid
            description: chave única da tabela.
          - name: name
            description: Nome da subcategoria

      - name: person_person
        description: Tabela de cadastro de dados de pessoas.
        columns:
          - name: businessentityid
            description: Chave primaria da tabela faz referencia a tabela BusinessEntity.
          - name: persontype
            description: Tipo de Pessoa.
          - name: namestyle
          - name: title
          - name: firstname
            description: Primeiro nome da Pessoa.
          - name: middlename
          - name: lastname
            description: Sobrenome da pessoa.
          - name: suffix
          - name: emailpromotion
          - name: additionalcontactinfo
          - name: demographics
          - name: rowguid
          - name: modifieddate

      - name: sales_salesorderheader
        description: Tabela de cadastro de pedidos de venda
        columns:
          - name: salesorderid
            description: Chave primaria da tabela
          - name: revisionnumber
          - name: orderdate
          - name: duedate
          - name: shipdate
          - name: status
          - name: onlineorderflag
          - name: purchaseordernumber
          - name: accountnumber
          - name: customerid
            description: Foreign key para a tabela sales.customer.
          - name: salespersonid
            description: Foreing key para a tabela sales.salesperson.
          - name: territoryid
            description: Foreing key para a tabela sales.salesterritory.
          - name: billtoaddressid
            description: Foreing key para a tabela person.adress, aponta o endereço de cobrança.
          - name: shiptoaddressid
            description: Foreing key para a tabela person.adress, aponta o endereço de envio do pedido.
          - name: shipmethodid
            description: Foreing key para a tabela purchasing.shipmethod.
          - name: creditcardid
            description: Foreing key para a tabela sales.creditcard.
          - name: creditcardapprovalcode
          - name: currencyrateid
            description: Foreing key para a tabela sales.currencyrate
          - name: subtotal
          - name: taxamt
          - name: freight
          - name: totaldue
          - name: comment
          - name: rowguid
          - name: modifieddate

      - name: sales_salesorderdetail
        description: Tabela de cadastro dos detalhes dos pedidos
        columns:
          - name: salesorderid
            description: Foreign key para a tabela sales.salesoderheader.
          - name: salesorderdetailid
            description: Primary key da tabela.
          - name: carriertrackingnumber
          - name: orderqty
            description: Quantidade de itens da ordem.
          - name: productid
            description: Foreign key para a tabela production.product
          - name: specialofferid
            description: Foreign key para a tabela sales.specialofferproduct.
          - name: unitprice
            description: Preço unitário do produto
          - name: unitpricediscount
            description: Desconto dado ao produto.
          - name: rowguid
          - name: modifieddate

      - name: sales_salesorderheadersalesreason
        description: Tabela relacional entre tabela sales.salesorderheader e sales.salesreason.
        columns:
          - name: salesorderid
            description: Foreign key da tabela sales.salesorderheader.
          - name: salesreasonid
            description: Foreign key da tabela sales.salesreason.
          - name: modifieddate

      - name: sales_salesreason
        description: Tabela de cadastro de motivos de venda.
        columns:
          - name: salesreasonid
            description: Chave primaria da tabela.
          - name: name
            description: Motivo da venda.
          - name: reasontype
            description: Tipificação/agrupador de motivo.
          - name: modifieddate

      - name: sales_personcreditcard
        description: Tabela relacional entre o cadastro de pessoa(person.person) e o cadastro de cartão de credito(sales.creditcard).
        columns:
          - name: businessentityid
            description: Foreign key com a tabela de pessoa(person.person).
          - name: creditcardid
            description: Foregin key com a tabela de cadastro de cartão de credito(sales.creditcard)
          - name: modifieddate

      - name: sales_creditcard
        description: Tabela de cadastro de cartões de credito.
        columns:
          - name: creditcardid
            description: Chave primária da tabela.
          - name: cardtype
            description: Bandeira do cartão de crédito.
          - name: cardnumber
            description: Número do Cartão.
          - name: expmonth
            description: Mês de vencimento do cartão, campo inteiro.
          - name: expyear
            description: Ano de vencimento do cartão, campo inteiro.
          - name: modifieddate

      - name: sales_salesterritory
        description: Tabela de cadastro de território de vendas.
        columns:
          - name: territoryid
            description: Chave Primária da tabela.
          - name: name
            description: nome do território.
          - name: countryregioncode
            description: País.
          - name: group
          - name: salesytd
            description: Vendas no território no ano atual.
          - name: saleslastyear
            description: Vendas totais no ano passado.
          - name: costytd
            description: Custo total até o ano corrente.
          - name: costlastyear
            description: Custo total ano passado.
          - name: rowguid
          - name: modifieddate

      - name: sales_salesperson
        description: Tabela de cadastro de vendedores.
        columns:
          - name: businessentityid
            description: Chave primária da tabela, faz referencia a tabela person.businessentity.
          - name: territoryid
            description: Foreign key para a tabela sales.salesterritory.
          - name: salesquota
          - name: bonus
          - name: commissionpct
          - name: salesytd
          - name: saleslastyear
          - name: rowguid
          - name: modifieddate

      - name: sales_store
        description: Tabela de cadastro de lojas.
        columns:
          - name: businessentityid
            description: Chave primária da tabela, faz referencia a tabela person.businessentity.
          - name: name
          - name: salespersonid
            description: Foreign key para a tabela sales.salesperson.
          - name: demographics
          - name: rowguid
          - name: modifieddate

      - name: sales_customer
        description: Tabela relacional entre pessoa e loja ou vendedor.
        columns:
          - name: customerid
            description: Chave primária da tabela.
          - name: personid
            description: Foreign Key relacionada com o campo businessentity da tabela person.person.
          - name: storeid
            description: Foreign Key relacionada com o campo businessentity da sales.store.
          - name: territoryid
            description: Foreign Key relacionada com tabela sales.salesterritory.
          - name: rowguid
          - name: modifieddate